from sheets import upsert_macro


upsert_macro("Policy_Rate", "4.25", source="NRB", unit="%")
upsert_macro("Bank_Rate", "5.75", source="NRB", unit="%")
upsert_macro("CRR_Percentage", "4.0", source="NRB", unit="%")
upsert_macro("SLR_Percentage", "12.0% (Commercial), 10.0% (Development), 7.0% (Finance)", source="NRB", unit="")
upsert_macro("CPI_Inflation", "3.25", source="NRB", unit="%")
upsert_macro("Credit_Growth_Rate", "6.8% (YoY)", source="NRB", unit="")
upsert_macro("Liquidity_Status", "Ample Surplus", source="NRB", unit="")
upsert_macro("Remittance_YoY_Change_Percent", "39.8% (NPR), 33.0% (USD)", source="NRB", unit="")
upsert_macro("FX_Reserve_Months", "18.0", source="NRB", unit="months")
upsert_macro("Overall_Sentiment", "Cautiously Accommodative / Transitioning", source="NRB", unit="")
upsert_macro("Forward_Guidance", "Continued easing of credit constraints and interest rate management to stimulate demand", source="NRB", unit="")
upsert_macro("Key_Risks", "Political instability, rising NPLs, slow credit demand, and global energy price volatility", source="NRB", unit="")
upsert_macro("BoP_Overall_Balance_USD_Million", "4030", source="NRB", unit="USD million")
upsert_macro("BoP_Current_Account_USD_Million", "3470", source="NRB", unit="USD million")
upsert_macro("BoP_Capital_Account_USD_Million", "78.92", source="NRB", unit="USD million")
upsert_macro("BoP_Trade_Deficit_USD_Million", "6596.27", source="NRB", unit="USD million")
upsert_macro("BoP_Status", "Surplus", source="NRB", unit="")
upsert_macro("BoP_Trend", "Increasing / Record Surplus", source="NRB", unit="")
upsert_macro("BoP_Impact_on_NEPSE", "Positive support due to high liquidity from remittance-led BoP surplus, but tempered by investor hesitancy", source="NRB", unit="")