"""
db/schema.py
AUTO-GENERATED by db/codegen.py — DO NOT EDIT MANUALLY.
Edit schema.prisma then run: python -m db.codegen
"""

TABS: dict[str, str] = {
    "price_history": "price_history",
    "market_breadth": "market_breadth",
    "portfolio": "portfolio",
    "market_log": "market_log",
    "indicators": "indicators",
    "candle_patterns": "candle_patterns",
    "candle_signals": "candle_signals",
    "geo_data": "geopolitical_data",
    "nepal_pulse": "nepal_pulse",
    "nrb_monthly": "nrb_monthly",
    "fundamentals": "fundamentals",
    "fundamental_beta": "fundamental_beta",
    "sector_momentum": "sector_momentum",
    "corporate_events": "corporate_events",
    "dividend_announcements": "dividend_announcements",
    "dividend_pattern_study": "dividend_pattern_study",
    "trade_journal": "trade_journal",
    "learning_hub": "learning_hub",
    "backtest_results": "backtest_results",
    "capital_allocation": "capital_allocation",
    "financial_advisor": "financial_advisor",
    "financials": "financials",
    "settings": "settings",
    "schema": "db_schema",
    "nepse_indices": "nepse_indices",
    "macro_stat_results": "macro_stat_results",
    "daily_context_log": "daily_context_log",
    "fd_rates": "fd_rates",
    "fd_rate_summary": "fd_rate_summary",
    "international_prices": "international_prices",
    "share_sectors": "share_sectors",
    "paper_users": "paper_users",
    "paper_capital": "paper_capital",
    "paper_portfolio": "paper_portfolio",
    "paper_trade_log": "paper_trade_log",
    "gate_misses": "gate_misses",
    "gate_proposals": "gate_proposals",
    "claude_audit": "claude_audit",
}

TABLE_DDL: dict[str, str] = {
    "price_history": """
    CREATE TABLE IF NOT EXISTS "price_history" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        symbol TEXT NOT NULL,
        open TEXT,
        high TEXT,
        low TEXT,
        close TEXT,
        ltp TEXT,
        volume TEXT,
        turnover TEXT,
        vwap TEXT,
        prev_close TEXT,
        transactions TEXT,
        conf_score TEXT,
        avg_120d TEXT,
        avg_180d TEXT,
        week52_high TEXT,
        week52_low TEXT,
        source TEXT DEFAULT 'sharesansar',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_price_history_date_symbol UNIQUE (date, symbol)
    );
    CREATE INDEX IF NOT EXISTS ix_price_history_symbol
        ON "price_history" (symbol);
    CREATE INDEX IF NOT EXISTS ix_price_history_date
        ON "price_history" (date);
    """,

    "market_breadth": """
    CREATE TABLE IF NOT EXISTS "market_breadth" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        advancing TEXT,
        declining TEXT,
        unchanged TEXT,
        new_52w_high TEXT,
        new_52w_low TEXT,
        total_turnover_npr TEXT,
        total_volume TEXT,
        breadth_score TEXT,
        market_signal TEXT,
        nepse_index TEXT,
        nepse_change_pct TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_market_breadth_date UNIQUE (date)
    );
    CREATE INDEX IF NOT EXISTS ix_market_breadth_date
        ON "market_breadth" (date);
    """,

    "portfolio": """
    CREATE TABLE IF NOT EXISTS "portfolio" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        entry_date TEXT,
        entry_price TEXT,
        shares TEXT,
        total_cost TEXT,
        current_price TEXT,
        current_value TEXT,
        pnl_npr TEXT,
        pnl_pct TEXT,
        peak_price TEXT,
        stop_type TEXT,
        stop_level TEXT,
        trail_active TEXT,
        trail_stop TEXT,
        status TEXT DEFAULT 'OPEN',
        exit_date TEXT,
        exit_price TEXT,
        exit_reason TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_portfolio_symbol
        ON "portfolio" (symbol);
    CREATE INDEX IF NOT EXISTS ix_portfolio_status
        ON "portfolio" (status);
    """,

    "market_log": """
    CREATE TABLE IF NOT EXISTS "market_log" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        symbol TEXT,
        sector TEXT,
        action TEXT,
        confidence TEXT,
        entry_price TEXT,
        stop_loss TEXT,
        target TEXT,
        allocation_npr TEXT,
        shares TEXT,
        breakeven TEXT,
        risk_reward TEXT,
        rsi_14 TEXT,
        ema_20 TEXT,
        ema_50 TEXT,
        ema_200 TEXT,
        macd_line TEXT,
        macd_signal TEXT,
        volume TEXT,
        volume_ratio TEXT,
        obv_trend TEXT,
        vwap TEXT,
        atr_14 TEXT,
        bollinger_upper TEXT,
        bollinger_lower TEXT,
        support_level TEXT,
        resistance_level TEXT,
        candle_pattern TEXT,
        conf_score TEXT,
        pe_ratio TEXT,
        eps TEXT,
        roe TEXT,
        npl_pct TEXT,
        fundamental_score TEXT,
        geo_score TEXT,
        macro_score TEXT,
        reasoning TEXT,
        outcome TEXT DEFAULT 'PENDING',
        actual_pnl TEXT,
        exit_price TEXT,
        exit_date TEXT,
        exit_reason TEXT,
        timestamp TEXT,
        eval_date TEXT,
        eval_geo_score TEXT,
        eval_nepal_score TEXT,
        eval_nepse_index TEXT,
        eval_market_state TEXT,
        eval_policy_rate TEXT,
        eval_fd_rate_pct TEXT,
        eval_geo_delta TEXT,
        eval_nepal_delta TEXT,
        eval_key_news TEXT,
        eval_price_change_pct TEXT,
        eval_nepse_change_pct TEXT,
        eval_alpha TEXT,
        headlines_politics TEXT,
        headlines_economy TEXT,
        headlines_stock TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_market_log_symbol
        ON "market_log" (symbol);
    CREATE INDEX IF NOT EXISTS ix_market_log_date
        ON "market_log" (date);
    CREATE INDEX IF NOT EXISTS ix_market_log_outcome
        ON "market_log" (outcome);
    """,

    "indicators": """
    CREATE TABLE IF NOT EXISTS "indicators" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        date TEXT NOT NULL,
        volume TEXT,
        history_days TEXT,
        rsi_14 TEXT,
        rsi_signal TEXT,
        ema_20 TEXT,
        ema_50 TEXT,
        ema_200 TEXT,
        ema_trend TEXT,
        ema_20_50_cross TEXT,
        ema_50_200_cross TEXT,
        macd_line TEXT,
        macd_signal TEXT,
        macd_histogram TEXT,
        macd_cross TEXT,
        bb_upper TEXT,
        bb_middle TEXT,
        bb_lower TEXT,
        bb_width TEXT,
        bb_pct_b TEXT,
        bb_signal TEXT,
        atr_14 TEXT,
        atr_pct TEXT,
        obv TEXT,
        obv_trend TEXT,
        support_level TEXT,
        resistance_level TEXT,
        tech_score TEXT,
        tech_signal TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_indicators_symbol_date UNIQUE (symbol, date)
    );
    CREATE INDEX IF NOT EXISTS ix_indicators_date
        ON "indicators" (date);
    CREATE INDEX IF NOT EXISTS ix_indicators_tech_signal
        ON "indicators" (tech_signal);
    """,

    "candle_patterns": """
    CREATE TABLE IF NOT EXISTS "candle_patterns" (
        id SERIAL PRIMARY KEY,
        pattern_name TEXT NOT NULL,
        type TEXT,
        tier TEXT,
        nepal_win_rate_pct TEXT,
        sample_size TEXT,
        avg_gain_pct TEXT,
        best_sector TEXT,
        best_rsi_range TEXT,
        volume_condition TEXT,
        reliability TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_candle_patterns_pattern_name UNIQUE (pattern_name)
    );
    """,

    "candle_signals": """
    CREATE TABLE IF NOT EXISTS "candle_signals" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        date TEXT NOT NULL,
        pattern_name TEXT NOT NULL,
        signal TEXT,
        tier TEXT,
        confidence TEXT,
        volume_confirmed TEXT,
        candles_used TEXT,
        description TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_candle_signals_symbol_date_pattern_name UNIQUE (symbol, date, pattern_name)
    );
    CREATE INDEX IF NOT EXISTS ix_candle_signals_date
        ON "candle_signals" (date);
    CREATE INDEX IF NOT EXISTS ix_candle_signals_symbol
        ON "candle_signals" (symbol);
    CREATE INDEX IF NOT EXISTS ix_candle_signals_signal
        ON "candle_signals" (signal);
    """,

    "geopolitical_data": """
    CREATE TABLE IF NOT EXISTS "geopolitical_data" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        crude_price TEXT,
        crude_change_pct TEXT,
        vix TEXT,
        vix_level TEXT,
        nifty TEXT,
        nifty_change_pct TEXT,
        dxy TEXT,
        gold_price TEXT,
        geo_score TEXT,
        status TEXT,
        key_event TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_geopolitical_data_date
        ON "geopolitical_data" (date);
    """,

    "nepal_pulse": """
    CREATE TABLE IF NOT EXISTS "nepal_pulse" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        policy_rate TEXT,
        policy_rate_change TEXT,
        nrb_event TEXT,
        sebon_event TEXT,
        circuit_breaker TEXT,
        ipo_fpo_active TEXT,
        ipo_fpo_detail TEXT,
        govt_stability TEXT,
        political_event TEXT,
        budget_season TEXT,
        budget_event TEXT,
        remittance_yoy_pct TEXT,
        inflation_pct TEXT,
        forex_reserve_months TEXT,
        bandh_today TEXT,
        bandh_detail TEXT,
        load_shedding_hrs TEXT,
        nepal_score TEXT,
        nepal_status TEXT,
        key_event TEXT,
        source TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_nepal_pulse_date
        ON "nepal_pulse" (date);
    """,

    "nrb_monthly": """
    CREATE TABLE IF NOT EXISTS "nrb_monthly" (
        id SERIAL PRIMARY KEY,
        period TEXT NOT NULL,
        fiscal_year TEXT,
        month_number TEXT,
        is_annual TEXT DEFAULT 'false',
        nepse_index TEXT,
        policy_rate TEXT,
        bank_rate TEXT,
        crr_percentage TEXT,
        slr_percentage TEXT,
        cpi_inflation TEXT,
        credit_growth_rate TEXT,
        liquidity_injected_billion TEXT,
        remittance_yoy_change_pct TEXT,
        fx_reserve_months TEXT,
        bop_overall_balance_usd_m TEXT,
        bop_current_account_usd_m TEXT,
        bop_status TEXT,
        bop_trend TEXT,
        overall_sentiment TEXT,
        forward_guidance TEXT,
        key_risks TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_nrb_monthly_period UNIQUE (period)
    );
    CREATE INDEX IF NOT EXISTS ix_nrb_monthly_fiscal_year_month_number
        ON "nrb_monthly" (fiscal_year, month_number);
    """,

    "fundamentals": """
    CREATE TABLE IF NOT EXISTS "fundamentals" (
        id TEXT NOT NULL PRIMARY KEY,
        symbol TEXT,
        stock_id TEXT,
        fiscal_year TEXT,
        quarter TEXT,
        eps TEXT,
        net_worth TEXT,
        roe TEXT,
        roa TEXT,
        paidup_capital TEXT,
        reserve TEXT,
        total_assets TEXT,
        total_liabilities TEXT,
        deposit TEXT,
        loan TEXT,
        net_interest_income TEXT,
        operating_profit TEXT,
        net_profit TEXT,
        npl TEXT,
        capital_fund_to_rwa TEXT,
        cost_of_fund TEXT,
        base_rate TEXT,
        interest_spread TEXT,
        cd_ratio TEXT,
        dps TEXT,
        sector_id TEXT,
        promoter_shares TEXT,
        public_shares TEXT,
        share_registar TEXT,
        is_delisted TEXT,
        is_merged TEXT,
        core_capital TEXT,
        gram_value TEXT,
        prev_quarter_profit TEXT,
        growth_rate TEXT,
        close TEXT,
        discount_rate TEXT,
        pe_ratio TEXT,
        peg_value TEXT,
        scraped_at TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fundamentals_symbol_fiscal_year_quarter UNIQUE (symbol, fiscal_year, quarter)
    );
    CREATE INDEX IF NOT EXISTS ix_fundamentals_symbol
        ON "fundamentals" (symbol);
    CREATE INDEX IF NOT EXISTS ix_fundamentals_fiscal_year_quarter
        ON "fundamentals" (fiscal_year, quarter);
    """,

    "fundamental_beta": """
    CREATE TABLE IF NOT EXISTS "fundamental_beta" (
        id TEXT NOT NULL PRIMARY KEY,
        symbol TEXT,
        beta TEXT,
        market_corr TEXT,
        market_corr_p TEXT,
        n_months TEXT,
        period_start TEXT,
        period_end TEXT,
        computed_date TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fundamental_beta_symbol_computed_date UNIQUE (symbol, computed_date)
    );
    CREATE INDEX IF NOT EXISTS ix_fundamental_beta_symbol
        ON "fundamental_beta" (symbol);
    """,

    "sector_momentum": """
    CREATE TABLE IF NOT EXISTS "sector_momentum" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        sector TEXT,
        weekly_return_pct TEXT,
        monthly_return_pct TEXT,
        avg_volume_change_pct TEXT,
        momentum_score TEXT,
        status TEXT,
        top_stock_1 TEXT,
        top_stock_2 TEXT,
        catalyst TEXT,
        last_updated TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_sector_momentum_date
        ON "sector_momentum" (date);
    CREATE INDEX IF NOT EXISTS ix_sector_momentum_sector
        ON "sector_momentum" (sector);
    """,

    "corporate_events": """
    CREATE TABLE IF NOT EXISTS "corporate_events" (
        id SERIAL PRIMARY KEY,
        symbol TEXT,
        company TEXT,
        event_type TEXT,
        announcement_date TEXT,
        event_date TEXT,
        book_close_date TEXT,
        details TEXT,
        expected_impact_pct TEXT,
        days_until_event TEXT,
        status TEXT,
        source TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_corporate_events_symbol
        ON "corporate_events" (symbol);
    CREATE INDEX IF NOT EXISTS ix_corporate_events_event_date
        ON "corporate_events" (event_date);
    """,

    "dividend_announcements": """
    CREATE TABLE IF NOT EXISTS "dividend_announcements" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        company TEXT,
        sector TEXT,
        announcement_date TEXT NOT NULL,
        fiscal_year TEXT,
        dividend_type TEXT,
        cash_dividend_pct TEXT,
        bonus_share_pct TEXT,
        total_dividend_pct TEXT,
        book_close_date TEXT,
        direction TEXT,
        prev_dividend_pct TEXT,
        source TEXT DEFAULT 'sharesansar',
        scraped_at TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_dividend_announcements_symbol_announcement_date UNIQUE (symbol, announcement_date)
    );
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_symbol
        ON "dividend_announcements" (symbol);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_announcement_date
        ON "dividend_announcements" (announcement_date);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_direction
        ON "dividend_announcements" (direction);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_sector
        ON "dividend_announcements" (sector);
    """,

    "dividend_pattern_study": """
    CREATE TABLE IF NOT EXISTS "dividend_pattern_study" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        announcement_date TEXT NOT NULL,
        sector TEXT,
        direction TEXT,
        price_drift_d10 TEXT,
        price_drift_d6 TEXT,
        price_drift_d4 TEXT,
        price_drift_d2 TEXT,
        vol_ratio_d6 TEXT,
        vol_ratio_d4 TEXT,
        vol_ratio_d2 TEXT,
        vol_ratio_d1 TEXT,
        rsi_d6 TEXT,
        rsi_d4 TEXT,
        obv_trend_d6_to_d1 TEXT,
        atr_ratio_d6 TEXT,
        macd_state_d4 TEXT,
        return_d0 TEXT,
        return_d1 TEXT,
        return_d2_d9 TEXT,
        vs_nepse_d1 TEXT,
        pattern_detected TEXT,
        pattern_type TEXT,
        pattern_strength TEXT,
        entry_feasible TEXT,
        optimal_entry_day TEXT,
        in_dividend_season TEXT,
        event_type TEXT,
        fiscal_year TEXT,
        dividend_type TEXT,
        run_date TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_dividend_pattern_study_symbol_announcement_date UNIQUE (symbol, announcement_date)
    );
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_symbol
        ON "dividend_pattern_study" (symbol);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_direction
        ON "dividend_pattern_study" (direction);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_pattern_detected
        ON "dividend_pattern_study" (pattern_detected);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_sector
        ON "dividend_pattern_study" (sector);
    """,

    "trade_journal": """
    CREATE TABLE IF NOT EXISTS "trade_journal" (
        id SERIAL PRIMARY KEY,
        created_at TEXT,
        symbol TEXT NOT NULL,
        sector TEXT,
        paper_mode TEXT,
        entry_date TEXT,
        entry_price TEXT,
        shares TEXT,
        allocation_npr TEXT,
        primary_signal TEXT,
        secondary_signal TEXT,
        candle_pattern TEXT,
        confidence_at_entry TEXT,
        rsi_entry TEXT,
        macd_hist_entry TEXT,
        bb_signal_entry TEXT,
        ema_trend_entry TEXT,
        obv_trend_entry TEXT,
        conf_score_entry TEXT,
        volume_ratio_entry TEXT,
        atr_pct_entry TEXT,
        market_state_entry TEXT,
        geo_score_entry TEXT,
        nepal_score_entry TEXT,
        combined_geo_entry TEXT,
        nepse_index_entry TEXT,
        stop_loss_planned TEXT,
        target_planned TEXT,
        hold_days_planned TEXT,
        exit_date TEXT,
        exit_price TEXT,
        exit_reason TEXT,
        market_state_exit TEXT,
        geo_score_exit TEXT,
        nepal_score_exit TEXT,
        combined_geo_exit TEXT,
        nepse_index_exit TEXT,
        hold_days_actual TEXT,
        return_pct TEXT,
        pnl_npr TEXT,
        result TEXT,
        geo_delta TEXT,
        nepal_delta TEXT,
        combined_geo_delta TEXT,
        nepse_return_pct TEXT,
        alpha_vs_nepse TEXT,
        loss_cause TEXT,
        lesson_ids TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_trade_journal_symbol
        ON "trade_journal" (symbol);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_result
        ON "trade_journal" (result);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_primary_signal
        ON "trade_journal" (primary_signal);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_entry_date
        ON "trade_journal" (entry_date);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_sector
        ON "trade_journal" (sector);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_loss_cause
        ON "trade_journal" (loss_cause);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_paper_mode
        ON "trade_journal" (paper_mode);
    """,

    "learning_hub": """
    CREATE TABLE IF NOT EXISTS "learning_hub" (
        id SERIAL PRIMARY KEY,
        created_at TEXT,
        lesson_type TEXT,
        source TEXT,
        symbol TEXT,
        sector TEXT,
        applies_to TEXT,
        condition TEXT,
        finding TEXT,
        action TEXT,
        trade_count TEXT,
        win_count TEXT,
        loss_count TEXT,
        win_rate TEXT,
        avg_return_pct TEXT,
        avg_pnl_npr TEXT,
        confidence_level TEXT,
        loss_cause_primary TEXT,
        geo_delta_avg TEXT,
        nepal_delta_avg TEXT,
        alpha_vs_nepse_avg TEXT,
        active TEXT DEFAULT 'true',
        superseded_by TEXT,
        supersedes_lesson_id TEXT,
        review_week TEXT,
        evidence_window_days TEXT,
        market_log_ids TEXT,
        gpt_reasoning TEXT,
        last_validated TEXT,
        validation_count TEXT,
        trade_journal_ids TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_learning_hub_symbol
        ON "learning_hub" (symbol);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_sector
        ON "learning_hub" (sector);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_lesson_type
        ON "learning_hub" (lesson_type);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_active
        ON "learning_hub" (active);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_source
        ON "learning_hub" (source);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_confidence_level
        ON "learning_hub" (confidence_level);
    """,

    "backtest_results": """
    CREATE TABLE IF NOT EXISTS "backtest_results" (
        id SERIAL PRIMARY KEY,
        test_name TEXT,
        parameter_tested TEXT,
        optimal_value TEXT,
        win_rate_at_optimal TEXT,
        sample_size TEXT,
        confidence TEXT,
        date_run TEXT,
        notes TEXT,
        sim_mode TEXT,
        period_start TEXT,
        period_end TEXT,
        total_trades TEXT,
        wins TEXT,
        losses TEXT,
        win_rate_pct TEXT,
        profit_factor TEXT,
        annual_ret_pct TEXT,
        total_pnl_npr TEXT,
        total_fees_npr TEXT,
        sharpe_ratio TEXT,
        max_drawdown_pct TEXT,
        alpha_vs_nepse TEXT,
        signal_breakdown TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    """,

    "capital_allocation": """
    CREATE TABLE IF NOT EXISTS "capital_allocation" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        market_state TEXT,
        nepse_vs_200dma TEXT,
        stocks_pct TEXT,
        fd_pct TEXT,
        savings_pct TEXT,
        od_pct TEXT,
        fd_rate_used TEXT,
        expected_return TEXT,
        reasoning TEXT,
        review_date TEXT,
        status TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_capital_allocation_date
        ON "capital_allocation" (date);
    """,

    "financial_advisor": """
    CREATE TABLE IF NOT EXISTS "financial_advisor" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        recommendation_type TEXT,
        market_phase TEXT,
        confidence_pct TEXT,
        capital_in_stocks_pct TEXT,
        capital_in_fd_pct TEXT,
        capital_in_savings_pct TEXT,
        capital_in_od_pct TEXT,
        three_month_outlook TEXT,
        expected_return_pct TEXT,
        fd_rate_used TEXT,
        trigger_to_change TEXT,
        review_date TEXT,
        actual_outcome TEXT,
        was_forecast_correct TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_financial_advisor_date
        ON "financial_advisor" (date);
    """,

    "financials": """
    CREATE TABLE IF NOT EXISTS "financials" (
        id SERIAL PRIMARY KEY,
        kpi_name TEXT NOT NULL,
        current_value TEXT,
        target_value TEXT,
        alert_level TEXT,
        status TEXT,
        last_updated TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_financials_kpi_name UNIQUE (kpi_name)
    );
    """,

    "settings": """
    CREATE TABLE IF NOT EXISTS "settings" (
        id SERIAL PRIMARY KEY,
        key TEXT NOT NULL,
        value TEXT,
        description TEXT,
        last_updated TEXT,
        set_by TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_settings_key UNIQUE (key)
    );
    """,

    "db_schema": """
    CREATE TABLE IF NOT EXISTS "db_schema" (
        id SERIAL PRIMARY KEY,
        migration_id TEXT NOT NULL,
        name TEXT NOT NULL,
        applied_at TEXT,
        rolled_back_at TEXT,
        status TEXT DEFAULT 'applied',
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_db_schema_migration_id UNIQUE (migration_id)
    );
    """,

    "nepse_indices": """
    CREATE TABLE IF NOT EXISTS "nepse_indices" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        index_id TEXT NOT NULL,
        index_name TEXT NOT NULL,
        current_value TEXT,
        high TEXT,
        low TEXT,
        change_abs TEXT,
        change_pct TEXT,
        week52_high TEXT,
        week52_low TEXT,
        turnover TEXT,
        volume TEXT,
        transactions TEXT,
        source TEXT DEFAULT 'nepalstock',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_nepse_indices_date_index_id UNIQUE (date, index_id)
    );
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_date
        ON "nepse_indices" (date);
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_index_id
        ON "nepse_indices" (index_id);
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_index_name
        ON "nepse_indices" (index_name);
    """,

    "macro_stat_results": """
    CREATE TABLE IF NOT EXISTS "macro_stat_results" (
        id SERIAL PRIMARY KEY,
        variable TEXT NOT NULL,
        variable_label TEXT,
        lag_months TEXT NOT NULL,
        spearman_rho TEXT,
        p_value TEXT,
        p_corrected TEXT,
        significant TEXT,
        effect_size TEXT,
        n_pairs TEXT,
        rho_3m_forward TEXT,
        p_3m_forward TEXT,
        n_pairs_3m TEXT,
        n_total_tests TEXT,
        alpha_corrected TEXT,
        run_date TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_macro_stat_results_variable_lag_months_run_date UNIQUE (variable, lag_months, run_date)
    );
    CREATE INDEX IF NOT EXISTS ix_macro_stat_results_variable
        ON "macro_stat_results" (variable);
    CREATE INDEX IF NOT EXISTS ix_macro_stat_results_run_date
        ON "macro_stat_results" (run_date);
    """,

    "daily_context_log": """
    CREATE TABLE IF NOT EXISTS "daily_context_log" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        geo_score_eod TEXT,
        nepal_score_eod TEXT,
        combined_score_eod TEXT,
        nepse_index_eod TEXT,
        nepse_change_pct TEXT,
        dxy_value TEXT,
        dxy_change_pct TEXT,
        market_state TEXT,
        advancing TEXT,
        declining TEXT,
        breadth_score TEXT,
        total_turnover_npr TEXT,
        policy_rate TEXT,
        fd_rate_pct TEXT,
        lending_rate TEXT,
        bop_status TEXT,
        overall_sentiment TEXT,
        key_events_summary TEXT,
        nepal_pulse_highlights TEXT,
        geo_summary TEXT,
        nrb_macro_summary TEXT,
        signals_summary TEXT,
        buy_count TEXT,
        wait_count TEXT,
        avoid_count TEXT,
        gate_miss_count TEXT,
        gate_top_category TEXT,
        gate_false_block_pct TEXT,
        signals_avg_confidence TEXT,
        source TEXT DEFAULT 'gemini_nightly',
        backfilled TEXT DEFAULT 'false',
        created_at TEXT,
        headlines_political TEXT,
        headlines_economy TEXT,
        headlines_nepse TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_daily_context_log_date UNIQUE (date)
    );
    CREATE INDEX IF NOT EXISTS ix_daily_context_log_date
        ON "daily_context_log" (date);
    """,

    "fd_rates": """
    CREATE TABLE IF NOT EXISTS "fd_rates" (
        id SERIAL PRIMARY KEY,
        fetch_date TEXT NOT NULL,
        institute_code TEXT,
        institute_name TEXT,
        product_name TEXT,
        interest_rate TEXT,
        interest_pct TEXT,
        tenure_label TEXT,
        tenure_months TEXT,
        tenure_category TEXT,
        minimum_balance TEXT,
        institute_type TEXT,
        source TEXT DEFAULT 'bankbyaj',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fd_rates_fetch_date_institute_code_product_name UNIQUE (fetch_date, institute_code, product_name)
    );
    CREATE INDEX IF NOT EXISTS ix_fd_rates_fetch_date
        ON "fd_rates" (fetch_date);
    CREATE INDEX IF NOT EXISTS ix_fd_rates_tenure_category
        ON "fd_rates" (tenure_category);
    CREATE INDEX IF NOT EXISTS ix_fd_rates_interest_pct
        ON "fd_rates" (interest_pct);
    """,

    "fd_rate_summary": """
    CREATE TABLE IF NOT EXISTS "fd_rate_summary" (
        id SERIAL PRIMARY KEY,
        fetch_date TEXT NOT NULL,
        avg_rate_pct TEXT,
        max_rate_pct TEXT,
        min_rate_pct TEXT,
        benchmark_rate_pct TEXT,
        benchmark_products TEXT,
        best_bank_name TEXT,
        best_bank_rate TEXT,
        best_tenure TEXT,
        rate_vs_prev_pct TEXT,
        rate_direction TEXT,
        fd_score_signal TEXT,
        total_products TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fd_rate_summary_fetch_date UNIQUE (fetch_date)
    );
    CREATE INDEX IF NOT EXISTS ix_fd_rate_summary_fetch_date
        ON "fd_rate_summary" (fetch_date);
    """,

    "international_prices": """
    CREATE TABLE IF NOT EXISTS "international_prices" (
        id TEXT,
        date TEXT,
        variable_name TEXT,
        close_price TEXT,
        source TEXT DEFAULT 'yfinance',
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_international_prices_date_variable_name
        ON "international_prices" (date, variable_name);
    """,

    "share_sectors": """
    CREATE TABLE IF NOT EXISTS "share_sectors" (
        id SERIAL PRIMARY KEY,
        externalid TEXT,
        companyname TEXT,
        symbol TEXT,
        securityname TEXT,
        status TEXT,
        companyemail TEXT,
        website TEXT,
        sectorname TEXT,
        regulatorybody TEXT,
        instrumenttype TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_share_sectors_externalid UNIQUE (externalid)
    );
    """,

    "paper_users": """
    CREATE TABLE IF NOT EXISTS "paper_users" (
        id SERIAL PRIMARY KEY,
        telegram_id TEXT NOT NULL,
        username TEXT,
        full_name TEXT,
        status TEXT DEFAULT 'PENDING',
        registered_at TEXT,
        approved_at TEXT,
        approved_by TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_paper_users_telegram_id UNIQUE (telegram_id)
    );
    CREATE INDEX IF NOT EXISTS ix_paper_users_status
        ON "paper_users" (status);
    """,

    "paper_capital": """
    CREATE TABLE IF NOT EXISTS "paper_capital" (
        id SERIAL PRIMARY KEY,
        telegram_id TEXT NOT NULL,
        starting_capital TEXT DEFAULT '100000',
        current_capital TEXT DEFAULT '100000',
        total_realised_pnl TEXT DEFAULT '0',
        total_fees_paid TEXT DEFAULT '0',
        total_cgt_paid TEXT DEFAULT '0',
        total_trades TEXT DEFAULT '0',
        total_wins TEXT DEFAULT '0',
        total_losses TEXT DEFAULT '0',
        last_updated TEXT,
        test_mode TEXT DEFAULT 'false',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_paper_capital_telegram_id UNIQUE (telegram_id)
    );
    CREATE INDEX IF NOT EXISTS ix_paper_capital_telegram_id
        ON "paper_capital" (telegram_id);
    """,

    "paper_portfolio": """
    CREATE TABLE IF NOT EXISTS "paper_portfolio" (
        id SERIAL PRIMARY KEY,
        telegram_id TEXT NOT NULL,
        symbol TEXT NOT NULL,
        status TEXT DEFAULT 'OPEN',
        total_shares TEXT,
        wacc TEXT,
        total_cost TEXT,
        first_buy_date TEXT,
        last_buy_date TEXT,
        buy_count TEXT DEFAULT '1',
        exit_date TEXT,
        exit_price TEXT,
        exit_shares TEXT,
        gross_pnl TEXT,
        sell_fees TEXT,
        cgt_paid TEXT,
        net_pnl TEXT,
        result TEXT,
        created_at TEXT,
        updated_at TEXT,
        test_mode TEXT DEFAULT 'false',
        audited TEXT DEFAULT 'false',
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_paper_portfolio_telegram_id
        ON "paper_portfolio" (telegram_id);
    CREATE INDEX IF NOT EXISTS ix_paper_portfolio_telegram_id_status
        ON "paper_portfolio" (telegram_id, status);
    CREATE INDEX IF NOT EXISTS ix_paper_portfolio_symbol
        ON "paper_portfolio" (symbol);
    CREATE INDEX IF NOT EXISTS ix_paper_portfolio_test_mode
        ON "paper_portfolio" (test_mode);
    """,

    "paper_trade_log": """
    CREATE TABLE IF NOT EXISTS "paper_trade_log" (
        id SERIAL PRIMARY KEY,
        telegram_id TEXT NOT NULL,
        symbol TEXT NOT NULL,
        action TEXT NOT NULL,
        shares TEXT,
        price TEXT,
        gross_amount TEXT,
        brokerage TEXT,
        sebon TEXT,
        dp_fee TEXT,
        cgt TEXT,
        total_fees TEXT,
        net_amount TEXT,
        capital_before TEXT,
        capital_after TEXT,
        wacc_before TEXT,
        wacc_after TEXT,
        note TEXT,
        created_at TEXT,
        test_mode TEXT DEFAULT 'false',
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_paper_trade_log_telegram_id
        ON "paper_trade_log" (telegram_id);
    CREATE INDEX IF NOT EXISTS ix_paper_trade_log_symbol
        ON "paper_trade_log" (symbol);
    CREATE INDEX IF NOT EXISTS ix_paper_trade_log_test_mode
        ON "paper_trade_log" (test_mode);
    """,

    "gate_misses": """
    CREATE TABLE IF NOT EXISTS "gate_misses" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        symbol TEXT NOT NULL,
        sector TEXT,
        gate_reason TEXT,
        gate_category TEXT,
        price_at_block TEXT,
        market_state TEXT,
        tech_score TEXT,
        conf_score TEXT,
        composite_score_would_be TEXT,
        tracking_days TEXT DEFAULT '0',
        outcome TEXT,
        outcome_return_pct TEXT,
        outcome_stamped_at TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_gate_misses_symbol_date UNIQUE (symbol, date)
    );
    CREATE INDEX IF NOT EXISTS ix_gate_misses_date
        ON "gate_misses" (date);
    CREATE INDEX IF NOT EXISTS ix_gate_misses_outcome
        ON "gate_misses" (outcome);
    CREATE INDEX IF NOT EXISTS ix_gate_misses_gate_category
        ON "gate_misses" (gate_category);
    """,

    "gate_proposals": """
    CREATE TABLE IF NOT EXISTS "gate_proposals" (
        id SERIAL PRIMARY KEY,
        review_week TEXT,
        proposal_number TEXT,
        parameter_name TEXT,
        current_value TEXT,
        proposed_value TEXT,
        reasoning TEXT,
        false_block_rate TEXT,
        sample_size TEXT,
        status TEXT DEFAULT 'PENDING',
        decided_at TEXT,
        applied_at TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_gate_proposals_review_week
        ON "gate_proposals" (review_week);
    CREATE INDEX IF NOT EXISTS ix_gate_proposals_status
        ON "gate_proposals" (status);
    """,

    "claude_audit": """
    CREATE TABLE IF NOT EXISTS "claude_audit" (
        id SERIAL PRIMARY KEY,
        review_week TEXT NOT NULL,
        buy_count TEXT,
        buy_win_rate TEXT,
        buy_avg_return TEXT,
        wait_count TEXT,
        wait_accuracy TEXT,
        avoid_count TEXT,
        avoid_accuracy TEXT,
        false_avoid_rate TEXT,
        missed_entry_rate TEXT,
        overall_accuracy TEXT,
        macro_accuracy TEXT,
        audit_summary TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_claude_audit_review_week UNIQUE (review_week)
    );
    """,
}

TABLE_COLUMNS: dict[str, list[str]] = {
    "price_history": ["date", "symbol", "open", "high", "low", "close", "ltp", "volume", "turnover", "vwap", "prev_close", "transactions", "conf_score", "avg_120d", "avg_180d", "week52_high", "week52_low", "source"],
    "market_breadth": ["date", "advancing", "declining", "unchanged", "new_52w_high", "new_52w_low", "total_turnover_npr", "total_volume", "breadth_score", "market_signal", "nepse_index", "nepse_change_pct", "timestamp"],
    "portfolio": ["symbol", "entry_date", "entry_price", "shares", "total_cost", "current_price", "current_value", "pnl_npr", "pnl_pct", "peak_price", "stop_type", "stop_level", "trail_active", "trail_stop", "status", "exit_date", "exit_price", "exit_reason"],
    "market_log": ["date", "time", "symbol", "sector", "action", "confidence", "entry_price", "stop_loss", "target", "allocation_npr", "shares", "breakeven", "risk_reward", "rsi_14", "ema_20", "ema_50", "ema_200", "macd_line", "macd_signal", "volume", "volume_ratio", "obv_trend", "vwap", "atr_14", "bollinger_upper", "bollinger_lower", "support_level", "resistance_level", "candle_pattern", "conf_score", "pe_ratio", "eps", "roe", "npl_pct", "fundamental_score", "geo_score", "macro_score", "reasoning", "outcome", "actual_pnl", "exit_price", "exit_date", "exit_reason", "timestamp", "eval_date", "eval_geo_score", "eval_nepal_score", "eval_nepse_index", "eval_market_state", "eval_policy_rate", "eval_fd_rate_pct", "eval_geo_delta", "eval_nepal_delta", "eval_key_news", "eval_price_change_pct", "eval_nepse_change_pct", "eval_alpha", "headlines_politics", "headlines_economy", "headlines_stock"],
    "indicators": ["symbol", "date", "volume", "history_days", "rsi_14", "rsi_signal", "ema_20", "ema_50", "ema_200", "ema_trend", "ema_20_50_cross", "ema_50_200_cross", "macd_line", "macd_signal", "macd_histogram", "macd_cross", "bb_upper", "bb_middle", "bb_lower", "bb_width", "bb_pct_b", "bb_signal", "atr_14", "atr_pct", "obv", "obv_trend", "support_level", "resistance_level", "tech_score", "tech_signal", "timestamp"],
    "candle_patterns": ["pattern_name", "type", "tier", "nepal_win_rate_pct", "sample_size", "avg_gain_pct", "best_sector", "best_rsi_range", "volume_condition", "reliability", "notes"],
    "candle_signals": ["symbol", "date", "pattern_name", "signal", "tier", "confidence", "volume_confirmed", "candles_used", "description", "timestamp"],
    "geopolitical_data": ["date", "time", "crude_price", "crude_change_pct", "vix", "vix_level", "nifty", "nifty_change_pct", "dxy", "gold_price", "geo_score", "status", "key_event", "timestamp"],
    "nepal_pulse": ["date", "time", "policy_rate", "policy_rate_change", "nrb_event", "sebon_event", "circuit_breaker", "ipo_fpo_active", "ipo_fpo_detail", "govt_stability", "political_event", "budget_season", "budget_event", "remittance_yoy_pct", "inflation_pct", "forex_reserve_months", "bandh_today", "bandh_detail", "load_shedding_hrs", "nepal_score", "nepal_status", "key_event", "source", "timestamp"],
    "nrb_monthly": ["period", "fiscal_year", "month_number", "is_annual", "nepse_index", "policy_rate", "bank_rate", "crr_percentage", "slr_percentage", "cpi_inflation", "credit_growth_rate", "liquidity_injected_billion", "remittance_yoy_change_pct", "fx_reserve_months", "bop_overall_balance_usd_m", "bop_current_account_usd_m", "bop_status", "bop_trend", "overall_sentiment", "forward_guidance", "key_risks"],
    "fundamentals": ["id", "symbol", "stock_id", "fiscal_year", "quarter", "eps", "net_worth", "roe", "roa", "paidup_capital", "reserve", "total_assets", "total_liabilities", "deposit", "loan", "net_interest_income", "operating_profit", "net_profit", "npl", "capital_fund_to_rwa", "cost_of_fund", "base_rate", "interest_spread", "cd_ratio", "dps", "sector_id", "promoter_shares", "public_shares", "share_registar", "is_delisted", "is_merged", "core_capital", "gram_value", "prev_quarter_profit", "growth_rate", "close", "discount_rate", "pe_ratio", "peg_value", "scraped_at"],
    "fundamental_beta": ["id", "symbol", "beta", "market_corr", "market_corr_p", "n_months", "period_start", "period_end", "computed_date"],
    "sector_momentum": ["date", "sector", "weekly_return_pct", "monthly_return_pct", "avg_volume_change_pct", "momentum_score", "status", "top_stock_1", "top_stock_2", "catalyst", "last_updated"],
    "corporate_events": ["symbol", "company", "event_type", "announcement_date", "event_date", "book_close_date", "details", "expected_impact_pct", "days_until_event", "status", "source"],
    "dividend_announcements": ["symbol", "company", "sector", "announcement_date", "fiscal_year", "dividend_type", "cash_dividend_pct", "bonus_share_pct", "total_dividend_pct", "book_close_date", "direction", "prev_dividend_pct", "source", "scraped_at"],
    "dividend_pattern_study": ["symbol", "announcement_date", "sector", "direction", "price_drift_d10", "price_drift_d6", "price_drift_d4", "price_drift_d2", "vol_ratio_d6", "vol_ratio_d4", "vol_ratio_d2", "vol_ratio_d1", "rsi_d6", "rsi_d4", "obv_trend_d6_to_d1", "atr_ratio_d6", "macd_state_d4", "return_d0", "return_d1", "return_d2_d9", "vs_nepse_d1", "pattern_detected", "pattern_type", "pattern_strength", "entry_feasible", "optimal_entry_day", "in_dividend_season", "event_type", "fiscal_year", "dividend_type", "run_date"],
    "trade_journal": ["created_at", "symbol", "sector", "paper_mode", "entry_date", "entry_price", "shares", "allocation_npr", "primary_signal", "secondary_signal", "candle_pattern", "confidence_at_entry", "rsi_entry", "macd_hist_entry", "bb_signal_entry", "ema_trend_entry", "obv_trend_entry", "conf_score_entry", "volume_ratio_entry", "atr_pct_entry", "market_state_entry", "geo_score_entry", "nepal_score_entry", "combined_geo_entry", "nepse_index_entry", "stop_loss_planned", "target_planned", "hold_days_planned", "exit_date", "exit_price", "exit_reason", "market_state_exit", "geo_score_exit", "nepal_score_exit", "combined_geo_exit", "nepse_index_exit", "hold_days_actual", "return_pct", "pnl_npr", "result", "geo_delta", "nepal_delta", "combined_geo_delta", "nepse_return_pct", "alpha_vs_nepse", "loss_cause", "lesson_ids"],
    "learning_hub": ["created_at", "lesson_type", "source", "symbol", "sector", "applies_to", "condition", "finding", "action", "trade_count", "win_count", "loss_count", "win_rate", "avg_return_pct", "avg_pnl_npr", "confidence_level", "loss_cause_primary", "geo_delta_avg", "nepal_delta_avg", "alpha_vs_nepse_avg", "active", "superseded_by", "supersedes_lesson_id", "review_week", "evidence_window_days", "market_log_ids", "gpt_reasoning", "last_validated", "validation_count", "trade_journal_ids"],
    "backtest_results": ["test_name", "parameter_tested", "optimal_value", "win_rate_at_optimal", "sample_size", "confidence", "date_run", "notes", "sim_mode", "period_start", "period_end", "total_trades", "wins", "losses", "win_rate_pct", "profit_factor", "annual_ret_pct", "total_pnl_npr", "total_fees_npr", "sharpe_ratio", "max_drawdown_pct", "alpha_vs_nepse", "signal_breakdown"],
    "capital_allocation": ["date", "market_state", "nepse_vs_200dma", "stocks_pct", "fd_pct", "savings_pct", "od_pct", "fd_rate_used", "expected_return", "reasoning", "review_date", "status"],
    "financial_advisor": ["date", "recommendation_type", "market_phase", "confidence_pct", "capital_in_stocks_pct", "capital_in_fd_pct", "capital_in_savings_pct", "capital_in_od_pct", "three_month_outlook", "expected_return_pct", "fd_rate_used", "trigger_to_change", "review_date", "actual_outcome", "was_forecast_correct"],
    "financials": ["kpi_name", "current_value", "target_value", "alert_level", "status", "last_updated", "notes"],
    "settings": ["key", "value", "description", "last_updated", "set_by"],
    "db_schema": ["migration_id", "name", "applied_at", "rolled_back_at", "status", "notes"],
    "nepse_indices": ["date", "index_id", "index_name", "current_value", "high", "low", "change_abs", "change_pct", "week52_high", "week52_low", "turnover", "volume", "transactions", "source"],
    "macro_stat_results": ["variable", "variable_label", "lag_months", "spearman_rho", "p_value", "p_corrected", "significant", "effect_size", "n_pairs", "rho_3m_forward", "p_3m_forward", "n_pairs_3m", "n_total_tests", "alpha_corrected", "run_date", "notes"],
    "daily_context_log": ["date", "geo_score_eod", "nepal_score_eod", "combined_score_eod", "nepse_index_eod", "nepse_change_pct", "dxy_value", "dxy_change_pct", "market_state", "advancing", "declining", "breadth_score", "total_turnover_npr", "policy_rate", "fd_rate_pct", "lending_rate", "bop_status", "overall_sentiment", "key_events_summary", "nepal_pulse_highlights", "geo_summary", "nrb_macro_summary", "signals_summary", "buy_count", "wait_count", "avoid_count", "gate_miss_count", "gate_top_category", "gate_false_block_pct", "signals_avg_confidence", "source", "backfilled", "created_at", "headlines_political", "headlines_economy", "headlines_nepse"],
    "fd_rates": ["fetch_date", "institute_code", "institute_name", "product_name", "interest_rate", "interest_pct", "tenure_label", "tenure_months", "tenure_category", "minimum_balance", "institute_type", "source"],
    "fd_rate_summary": ["fetch_date", "avg_rate_pct", "max_rate_pct", "min_rate_pct", "benchmark_rate_pct", "benchmark_products", "best_bank_name", "best_bank_rate", "best_tenure", "rate_vs_prev_pct", "rate_direction", "fd_score_signal", "total_products"],
    "international_prices": ["id", "date", "variable_name", "close_price", "source"],
    "share_sectors": ["externalid", "companyname", "symbol", "securityname", "status", "companyemail", "website", "sectorname", "regulatorybody", "instrumenttype"],
    "paper_users": ["telegram_id", "username", "full_name", "status", "registered_at", "approved_at", "approved_by"],
    "paper_capital": ["telegram_id", "starting_capital", "current_capital", "total_realised_pnl", "total_fees_paid", "total_cgt_paid", "total_trades", "total_wins", "total_losses", "last_updated", "test_mode"],
    "paper_portfolio": ["telegram_id", "symbol", "status", "total_shares", "wacc", "total_cost", "first_buy_date", "last_buy_date", "buy_count", "exit_date", "exit_price", "exit_shares", "gross_pnl", "sell_fees", "cgt_paid", "net_pnl", "result", "created_at", "updated_at", "test_mode", "audited"],
    "paper_trade_log": ["telegram_id", "symbol", "action", "shares", "price", "gross_amount", "brokerage", "sebon", "dp_fee", "cgt", "total_fees", "net_amount", "capital_before", "capital_after", "wacc_before", "wacc_after", "note", "created_at", "test_mode"],
    "gate_misses": ["date", "symbol", "sector", "gate_reason", "gate_category", "price_at_block", "market_state", "tech_score", "conf_score", "composite_score_would_be", "tracking_days", "outcome", "outcome_return_pct", "outcome_stamped_at"],
    "gate_proposals": ["review_week", "proposal_number", "parameter_name", "current_value", "proposed_value", "reasoning", "false_block_rate", "sample_size", "status", "decided_at", "applied_at"],
    "claude_audit": ["review_week", "buy_count", "buy_win_rate", "buy_avg_return", "wait_count", "wait_accuracy", "avoid_count", "avoid_accuracy", "false_avoid_rate", "missed_entry_rate", "overall_accuracy", "macro_accuracy", "audit_summary"],
}
