"""
db/schema.py
AUTO-GENERATED by db/codegen.py — DO NOT EDIT MANUALLY.
Edit schema.prisma then run: python -m db.codegen
"""

TABS: dict[str, str] = {
    "price_history": "price_history",
    "market_breadth": "market_breadth",
    "watchlist": "watchlist",
    "portfolio": "portfolio",
    "market_log": "market_log",
    "indicators": "indicators",
    "candle_patterns": "candle_patterns",
    "candle_signals": "candle_signals",
    "geo_data": "geopolitical_data",
    "nepal_pulse": "nepal_pulse",
    "macro_data": "macro_data",
    "nrb_monthly": "nrb_monthly",
    "fundamentals": "fundamentals",
    "sector_momentum": "sector_momentum",
    "corporate_events": "corporate_events",
    "dividend_announcements": "dividend_announcements",
    "dividend_pattern_study": "dividend_pattern_study",
    "trade_journal": "trade_journal",
    "learning_hub": "learning_hub",
    "news_sentiment": "news_sentiment",
    "backtest_results": "backtest_results",
    "capital_allocation": "capital_allocation",
    "financial_advisor": "financial_advisor",
    "financials": "financials",
    "settings": "settings",
    "schema": "db_schema",
    "nepse_indices": "nepse_indices",
    "macro_stat_results": "macro_stat_results",
    "fd_rates": "fd_rates",
    "fd_rate_summary": "fd_rate_summary",
}

TABLE_DDL: dict[str, str] = {
    "price_history": """
    CREATE TABLE IF NOT EXISTS "price_history" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        symbol TEXT NOT NULL,
        open TEXT,
        high TEXT,
        low TEXT,
        close TEXT,
        ltp TEXT,
        volume TEXT,
        turnover TEXT,
        vwap TEXT,
        prev_close TEXT,
        transactions TEXT,
        conf_score TEXT,
        avg_120d TEXT,
        avg_180d TEXT,
        week52_high TEXT,
        week52_low TEXT,
        source TEXT DEFAULT 'sharesansar',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_price_history_date_symbol UNIQUE (date, symbol)
    );
    CREATE INDEX IF NOT EXISTS ix_price_history_symbol
        ON "price_history" (symbol);
    CREATE INDEX IF NOT EXISTS ix_price_history_date
        ON "price_history" (date);
    """,

    "market_breadth": """
    CREATE TABLE IF NOT EXISTS "market_breadth" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        advancing TEXT,
        declining TEXT,
        unchanged TEXT,
        new_52w_high TEXT,
        new_52w_low TEXT,
        total_turnover_npr TEXT,
        total_volume TEXT,
        breadth_score TEXT,
        market_signal TEXT,
        nepse_index TEXT,
        nepse_change_pct TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_market_breadth_date UNIQUE (date)
    );
    CREATE INDEX IF NOT EXISTS ix_market_breadth_date
        ON "market_breadth" (date);
    """,

    "watchlist": """
    CREATE TABLE IF NOT EXISTS "watchlist" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        company TEXT,
        sector TEXT,
        added_date TEXT,
        fundamental_score TEXT,
        technical_score TEXT,
        combined_score TEXT,
        last_updated TEXT,
        sector_momentum TEXT,
        dividend_yield_pct TEXT,
        pe_ratio TEXT,
        eps TEXT,
        npl_pct TEXT,
        car_pct TEXT,
        week52_high TEXT,
        week52_low TEXT,
        pct_from_52w_high TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_watchlist_symbol UNIQUE (symbol)
    );
    CREATE INDEX IF NOT EXISTS ix_watchlist_sector
        ON "watchlist" (sector);
    """,

    "portfolio": """
    CREATE TABLE IF NOT EXISTS "portfolio" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        entry_date TEXT,
        entry_price TEXT,
        shares TEXT,
        total_cost TEXT,
        current_price TEXT,
        current_value TEXT,
        pnl_npr TEXT,
        pnl_pct TEXT,
        peak_price TEXT,
        stop_type TEXT,
        stop_level TEXT,
        trail_active TEXT,
        trail_stop TEXT,
        status TEXT DEFAULT 'OPEN',
        exit_date TEXT,
        exit_price TEXT,
        exit_reason TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_portfolio_symbol
        ON "portfolio" (symbol);
    CREATE INDEX IF NOT EXISTS ix_portfolio_status
        ON "portfolio" (status);
    """,

    "market_log": """
    CREATE TABLE IF NOT EXISTS "market_log" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        symbol TEXT,
        sector TEXT,
        action TEXT,
        confidence TEXT,
        entry_price TEXT,
        stop_loss TEXT,
        target TEXT,
        allocation_npr TEXT,
        shares TEXT,
        breakeven TEXT,
        risk_reward TEXT,
        rsi_14 TEXT,
        ema_20 TEXT,
        ema_50 TEXT,
        ema_200 TEXT,
        macd_line TEXT,
        macd_signal TEXT,
        volume TEXT,
        volume_ratio TEXT,
        obv_trend TEXT,
        vwap TEXT,
        atr_14 TEXT,
        bollinger_upper TEXT,
        bollinger_lower TEXT,
        support_level TEXT,
        resistance_level TEXT,
        candle_pattern TEXT,
        conf_score TEXT,
        pe_ratio TEXT,
        eps TEXT,
        roe TEXT,
        npl_pct TEXT,
        fundamental_score TEXT,
        geo_score TEXT,
        macro_score TEXT,
        reasoning TEXT,
        outcome TEXT DEFAULT 'PENDING',
        actual_pnl TEXT,
        exit_price TEXT,
        exit_date TEXT,
        exit_reason TEXT,
        dual_audit TEXT,
        gpt_verdict TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_market_log_symbol
        ON "market_log" (symbol);
    CREATE INDEX IF NOT EXISTS ix_market_log_date
        ON "market_log" (date);
    CREATE INDEX IF NOT EXISTS ix_market_log_outcome
        ON "market_log" (outcome);
    """,

    "indicators": """
    CREATE TABLE IF NOT EXISTS "indicators" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        date TEXT NOT NULL,
        ltp TEXT,
        prev_close TEXT,
        volume TEXT,
        history_days TEXT,
        rsi_14 TEXT,
        rsi_signal TEXT,
        ema_20 TEXT,
        ema_50 TEXT,
        ema_200 TEXT,
        ema_trend TEXT,
        ema_20_50_cross TEXT,
        ema_50_200_cross TEXT,
        macd_line TEXT,
        macd_signal TEXT,
        macd_histogram TEXT,
        macd_cross TEXT,
        bb_upper TEXT,
        bb_middle TEXT,
        bb_lower TEXT,
        bb_width TEXT,
        bb_pct_b TEXT,
        bb_signal TEXT,
        atr_14 TEXT,
        atr_pct TEXT,
        obv TEXT,
        obv_trend TEXT,
        tech_score TEXT,
        tech_signal TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_indicators_symbol_date UNIQUE (symbol, date)
    );
    CREATE INDEX IF NOT EXISTS ix_indicators_date
        ON "indicators" (date);
    CREATE INDEX IF NOT EXISTS ix_indicators_tech_signal
        ON "indicators" (tech_signal);
    """,

    "candle_patterns": """
    CREATE TABLE IF NOT EXISTS "candle_patterns" (
        id SERIAL PRIMARY KEY,
        pattern_name TEXT NOT NULL,
        type TEXT,
        tier TEXT,
        nepal_win_rate_pct TEXT,
        sample_size TEXT,
        avg_gain_pct TEXT,
        best_sector TEXT,
        best_rsi_range TEXT,
        volume_condition TEXT,
        reliability TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_candle_patterns_pattern_name UNIQUE (pattern_name)
    );
    """,

    "candle_signals": """
    CREATE TABLE IF NOT EXISTS "candle_signals" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        date TEXT NOT NULL,
        pattern_name TEXT NOT NULL,
        signal TEXT,
        tier TEXT,
        confidence TEXT,
        volume_confirmed TEXT,
        candles_used TEXT,
        description TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_candle_signals_symbol_date_pattern_name UNIQUE (symbol, date, pattern_name)
    );
    CREATE INDEX IF NOT EXISTS ix_candle_signals_date
        ON "candle_signals" (date);
    CREATE INDEX IF NOT EXISTS ix_candle_signals_symbol
        ON "candle_signals" (symbol);
    CREATE INDEX IF NOT EXISTS ix_candle_signals_signal
        ON "candle_signals" (signal);
    """,

    "geopolitical_data": """
    CREATE TABLE IF NOT EXISTS "geopolitical_data" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        crude_price TEXT,
        crude_change_pct TEXT,
        vix TEXT,
        vix_level TEXT,
        nifty TEXT,
        nifty_change_pct TEXT,
        dxy TEXT,
        gold_price TEXT,
        geo_score TEXT,
        status TEXT,
        key_event TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_geopolitical_data_date
        ON "geopolitical_data" (date);
    """,

    "nepal_pulse": """
    CREATE TABLE IF NOT EXISTS "nepal_pulse" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        time TEXT,
        policy_rate TEXT,
        policy_rate_change TEXT,
        ccd_ratio TEXT,
        crr TEXT,
        slr TEXT,
        nrb_event TEXT,
        sebon_event TEXT,
        circuit_breaker TEXT,
        ipo_fpo_active TEXT,
        ipo_fpo_detail TEXT,
        govt_stability TEXT,
        political_event TEXT,
        budget_season TEXT,
        budget_event TEXT,
        remittance_yoy_pct TEXT,
        inflation_pct TEXT,
        forex_reserve_months TEXT,
        trade_deficit_npr TEXT,
        bandh_today TEXT,
        bandh_detail TEXT,
        load_shedding_hrs TEXT,
        nepal_score TEXT,
        nepal_status TEXT,
        key_event TEXT,
        source TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_nepal_pulse_date
        ON "nepal_pulse" (date);
    """,

    "macro_data": """
    CREATE TABLE IF NOT EXISTS "macro_data" (
        id SERIAL PRIMARY KEY,
        indicator TEXT NOT NULL,
        value TEXT,
        unit TEXT,
        direction TEXT,
        impact TEXT,
        last_updated TEXT,
        source TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_macro_data_indicator UNIQUE (indicator)
    );
    """,

    "nrb_monthly": """
    CREATE TABLE IF NOT EXISTS "nrb_monthly" (
        id SERIAL PRIMARY KEY,
        period TEXT NOT NULL,
        fiscal_year TEXT,
        month_number TEXT,
        is_annual TEXT DEFAULT 'false',
        nepse_index TEXT,
        policy_rate TEXT,
        bank_rate TEXT,
        crr_percentage TEXT,
        slr_percentage TEXT,
        cpi_inflation TEXT,
        credit_growth_rate TEXT,
        liquidity_injected_billion TEXT,
        remittance_yoy_change_pct TEXT,
        fx_reserve_months TEXT,
        bop_overall_balance_usd_m TEXT,
        bop_current_account_usd_m TEXT,
        bop_status TEXT,
        bop_trend TEXT,
        overall_sentiment TEXT,
        forward_guidance TEXT,
        key_risks TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_nrb_monthly_period UNIQUE (period)
    );
    CREATE INDEX IF NOT EXISTS ix_nrb_monthly_fiscal_year_month_number
        ON "nrb_monthly" (fiscal_year, month_number);
    """,

    "fundamentals": """
    CREATE TABLE IF NOT EXISTS "fundamentals" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        company TEXT,
        sector TEXT,
        quarter TEXT,
        fiscal_year TEXT,
        eps TEXT,
        pe_ratio TEXT,
        bvps TEXT,
        pbv_ratio TEXT,
        roe TEXT,
        roa TEXT,
        dps TEXT,
        dividend_yield TEXT,
        net_profit_npr TEXT,
        revenue_npr TEXT,
        net_profit_growth_pct TEXT,
        revenue_growth_pct TEXT,
        debt_to_equity TEXT,
        market_cap_npr TEXT,
        car_pct TEXT,
        npl_pct TEXT,
        nim_pct TEXT,
        cd_ratio TEXT,
        report_date TEXT,
        data_source TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_fundamentals_symbol
        ON "fundamentals" (symbol);
    CREATE INDEX IF NOT EXISTS ix_fundamentals_quarter_fiscal_year
        ON "fundamentals" (quarter, fiscal_year);
    """,

    "sector_momentum": """
    CREATE TABLE IF NOT EXISTS "sector_momentum" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        sector TEXT,
        weekly_return_pct TEXT,
        monthly_return_pct TEXT,
        avg_volume_change_pct TEXT,
        momentum_score TEXT,
        status TEXT,
        top_stock_1 TEXT,
        top_stock_2 TEXT,
        catalyst TEXT,
        last_updated TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_sector_momentum_date
        ON "sector_momentum" (date);
    CREATE INDEX IF NOT EXISTS ix_sector_momentum_sector
        ON "sector_momentum" (sector);
    """,

    "corporate_events": """
    CREATE TABLE IF NOT EXISTS "corporate_events" (
        id SERIAL PRIMARY KEY,
        symbol TEXT,
        company TEXT,
        event_type TEXT,
        announcement_date TEXT,
        event_date TEXT,
        book_close_date TEXT,
        details TEXT,
        expected_impact_pct TEXT,
        days_until_event TEXT,
        status TEXT,
        source TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_corporate_events_symbol
        ON "corporate_events" (symbol);
    CREATE INDEX IF NOT EXISTS ix_corporate_events_event_date
        ON "corporate_events" (event_date);
    """,

    "dividend_announcements": """
    CREATE TABLE IF NOT EXISTS "dividend_announcements" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        company TEXT,
        sector TEXT,
        announcement_date TEXT NOT NULL,
        fiscal_year TEXT,
        dividend_type TEXT,
        cash_dividend_pct TEXT,
        bonus_share_pct TEXT,
        total_dividend_pct TEXT,
        book_close_date TEXT,
        direction TEXT,
        prev_dividend_pct TEXT,
        source TEXT DEFAULT 'sharesansar',
        scraped_at TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_dividend_announcements_symbol_announcement_date UNIQUE (symbol, announcement_date)
    );
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_symbol
        ON "dividend_announcements" (symbol);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_announcement_date
        ON "dividend_announcements" (announcement_date);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_direction
        ON "dividend_announcements" (direction);
    CREATE INDEX IF NOT EXISTS ix_dividend_announcements_sector
        ON "dividend_announcements" (sector);
    """,

    "dividend_pattern_study": """
    CREATE TABLE IF NOT EXISTS "dividend_pattern_study" (
        id SERIAL PRIMARY KEY,
        symbol TEXT NOT NULL,
        announcement_date TEXT NOT NULL,
        sector TEXT,
        direction TEXT,
        price_drift_d10 TEXT,
        price_drift_d6 TEXT,
        price_drift_d4 TEXT,
        price_drift_d2 TEXT,
        vol_ratio_d6 TEXT,
        vol_ratio_d4 TEXT,
        vol_ratio_d2 TEXT,
        vol_ratio_d1 TEXT,
        rsi_d6 TEXT,
        rsi_d4 TEXT,
        obv_trend_d6_to_d1 TEXT,
        atr_ratio_d6 TEXT,
        macd_state_d4 TEXT,
        return_d0 TEXT,
        return_d1 TEXT,
        return_d2_d9 TEXT,
        vs_nepse_d1 TEXT,
        pattern_detected TEXT,
        pattern_type TEXT,
        pattern_strength TEXT,
        entry_feasible TEXT,
        optimal_entry_day TEXT,
        run_date TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_dividend_pattern_study_symbol_announcement_date UNIQUE (symbol, announcement_date)
    );
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_symbol
        ON "dividend_pattern_study" (symbol);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_direction
        ON "dividend_pattern_study" (direction);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_pattern_detected
        ON "dividend_pattern_study" (pattern_detected);
    CREATE INDEX IF NOT EXISTS ix_dividend_pattern_study_sector
        ON "dividend_pattern_study" (sector);
    """,

    "trade_journal": """
    CREATE TABLE IF NOT EXISTS "trade_journal" (
        id SERIAL PRIMARY KEY,
        created_at TEXT,
        symbol TEXT NOT NULL,
        sector TEXT,
        paper_mode TEXT,
        entry_date TEXT,
        entry_price TEXT,
        shares TEXT,
        allocation_npr TEXT,
        primary_signal TEXT,
        secondary_signal TEXT,
        candle_pattern TEXT,
        confidence_at_entry TEXT,
        rsi_entry TEXT,
        macd_hist_entry TEXT,
        bb_signal_entry TEXT,
        ema_trend_entry TEXT,
        obv_trend_entry TEXT,
        conf_score_entry TEXT,
        volume_ratio_entry TEXT,
        atr_pct_entry TEXT,
        market_state_entry TEXT,
        geo_score_entry TEXT,
        nepal_score_entry TEXT,
        combined_geo_entry TEXT,
        nepse_index_entry TEXT,
        stop_loss_planned TEXT,
        target_planned TEXT,
        hold_days_planned TEXT,
        exit_date TEXT,
        exit_price TEXT,
        exit_reason TEXT,
        market_state_exit TEXT,
        geo_score_exit TEXT,
        nepal_score_exit TEXT,
        combined_geo_exit TEXT,
        nepse_index_exit TEXT,
        hold_days_actual TEXT,
        return_pct TEXT,
        pnl_npr TEXT,
        result TEXT,
        geo_delta TEXT,
        nepal_delta TEXT,
        combined_geo_delta TEXT,
        nepse_return_pct TEXT,
        alpha_vs_nepse TEXT,
        loss_cause TEXT,
        lesson_ids TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_trade_journal_symbol
        ON "trade_journal" (symbol);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_result
        ON "trade_journal" (result);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_primary_signal
        ON "trade_journal" (primary_signal);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_entry_date
        ON "trade_journal" (entry_date);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_sector
        ON "trade_journal" (sector);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_loss_cause
        ON "trade_journal" (loss_cause);
    CREATE INDEX IF NOT EXISTS ix_trade_journal_paper_mode
        ON "trade_journal" (paper_mode);
    """,

    "learning_hub": """
    CREATE TABLE IF NOT EXISTS "learning_hub" (
        id SERIAL PRIMARY KEY,
        created_at TEXT,
        lesson_type TEXT,
        source TEXT,
        symbol TEXT,
        sector TEXT,
        applies_to TEXT,
        condition TEXT,
        finding TEXT,
        action TEXT,
        trade_count TEXT,
        win_count TEXT,
        loss_count TEXT,
        win_rate TEXT,
        avg_return_pct TEXT,
        avg_pnl_npr TEXT,
        confidence_level TEXT,
        loss_cause_primary TEXT,
        geo_delta_avg TEXT,
        nepal_delta_avg TEXT,
        alpha_vs_nepse_avg TEXT,
        active TEXT DEFAULT 'true',
        superseded_by TEXT,
        last_validated TEXT,
        validation_count TEXT,
        trade_journal_ids TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_learning_hub_symbol
        ON "learning_hub" (symbol);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_sector
        ON "learning_hub" (sector);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_lesson_type
        ON "learning_hub" (lesson_type);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_active
        ON "learning_hub" (active);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_source
        ON "learning_hub" (source);
    CREATE INDEX IF NOT EXISTS ix_learning_hub_confidence_level
        ON "learning_hub" (confidence_level);
    """,

    "news_sentiment": """
    CREATE TABLE IF NOT EXISTS "news_sentiment" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        overall_score TEXT,
        banking_score TEXT,
        hydro_score TEXT,
        insurance_score TEXT,
        microfinance_score TEXT,
        top_positive_news TEXT,
        top_negative_news TEXT,
        key_stock_mentions TEXT,
        source_count TEXT,
        timestamp TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_news_sentiment_date
        ON "news_sentiment" (date);
    """,

    "backtest_results": """
    CREATE TABLE IF NOT EXISTS "backtest_results" (
        id SERIAL PRIMARY KEY,
        test_name TEXT,
        parameter_tested TEXT,
        optimal_value TEXT,
        win_rate_at_optimal TEXT,
        sample_size TEXT,
        confidence TEXT,
        date_run TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    """,

    "capital_allocation": """
    CREATE TABLE IF NOT EXISTS "capital_allocation" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        market_state TEXT,
        nepse_vs_200dma TEXT,
        stocks_pct TEXT,
        fd_pct TEXT,
        savings_pct TEXT,
        od_pct TEXT,
        fd_rate_used TEXT,
        expected_return TEXT,
        reasoning TEXT,
        review_date TEXT,
        status TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_capital_allocation_date
        ON "capital_allocation" (date);
    """,

    "financial_advisor": """
    CREATE TABLE IF NOT EXISTS "financial_advisor" (
        id SERIAL PRIMARY KEY,
        date TEXT,
        recommendation_type TEXT,
        market_phase TEXT,
        confidence_pct TEXT,
        capital_in_stocks_pct TEXT,
        capital_in_fd_pct TEXT,
        capital_in_savings_pct TEXT,
        capital_in_od_pct TEXT,
        three_month_outlook TEXT,
        expected_return_pct TEXT,
        fd_rate_used TEXT,
        trigger_to_change TEXT,
        review_date TEXT,
        actual_outcome TEXT,
        was_forecast_correct TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS ix_financial_advisor_date
        ON "financial_advisor" (date);
    """,

    "financials": """
    CREATE TABLE IF NOT EXISTS "financials" (
        id SERIAL PRIMARY KEY,
        kpi_name TEXT NOT NULL,
        current_value TEXT,
        target_value TEXT,
        alert_level TEXT,
        status TEXT,
        last_updated TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_financials_kpi_name UNIQUE (kpi_name)
    );
    """,

    "settings": """
    CREATE TABLE IF NOT EXISTS "settings" (
        id SERIAL PRIMARY KEY,
        key TEXT NOT NULL,
        value TEXT,
        description TEXT,
        last_updated TEXT,
        set_by TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_settings_key UNIQUE (key)
    );
    """,

    "db_schema": """
    CREATE TABLE IF NOT EXISTS "db_schema" (
        id SERIAL PRIMARY KEY,
        migration_id TEXT NOT NULL,
        name TEXT NOT NULL,
        applied_at TEXT,
        rolled_back_at TEXT,
        status TEXT DEFAULT 'applied',
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_db_schema_migration_id UNIQUE (migration_id)
    );
    """,

    "nepse_indices": """
    CREATE TABLE IF NOT EXISTS "nepse_indices" (
        id SERIAL PRIMARY KEY,
        date TEXT NOT NULL,
        index_id TEXT NOT NULL,
        index_name TEXT NOT NULL,
        current_value TEXT,
        high TEXT,
        low TEXT,
        change_abs TEXT,
        change_pct TEXT,
        week52_high TEXT,
        week52_low TEXT,
        turnover TEXT,
        volume TEXT,
        transactions TEXT,
        source TEXT DEFAULT 'nepalstock',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_nepse_indices_date_index_id UNIQUE (date, index_id)
    );
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_date
        ON "nepse_indices" (date);
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_index_id
        ON "nepse_indices" (index_id);
    CREATE INDEX IF NOT EXISTS ix_nepse_indices_index_name
        ON "nepse_indices" (index_name);
    """,

    "macro_stat_results": """
    CREATE TABLE IF NOT EXISTS "macro_stat_results" (
        id SERIAL PRIMARY KEY,
        variable TEXT NOT NULL,
        variable_label TEXT,
        lag_months TEXT NOT NULL,
        spearman_rho TEXT,
        p_value TEXT,
        p_corrected TEXT,
        significant TEXT,
        effect_size TEXT,
        n_pairs TEXT,
        rho_3m_forward TEXT,
        p_3m_forward TEXT,
        n_pairs_3m TEXT,
        n_total_tests TEXT,
        alpha_corrected TEXT,
        run_date TEXT,
        notes TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_macro_stat_results_variable_lag_months_run_date UNIQUE (variable, lag_months, run_date)
    );
    CREATE INDEX IF NOT EXISTS ix_macro_stat_results_variable
        ON "macro_stat_results" (variable);
    CREATE INDEX IF NOT EXISTS ix_macro_stat_results_run_date
        ON "macro_stat_results" (run_date);
    """,

    "fd_rates": """
    CREATE TABLE IF NOT EXISTS "fd_rates" (
        id SERIAL PRIMARY KEY,
        fetch_date TEXT NOT NULL,
        institute_code TEXT,
        institute_name TEXT,
        product_name TEXT,
        interest_rate TEXT,
        interest_pct TEXT,
        tenure_label TEXT,
        tenure_months TEXT,
        tenure_category TEXT,
        minimum_balance TEXT,
        institute_type TEXT,
        source TEXT DEFAULT 'bankbyaj',
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fd_rates_fetch_date_institute_code_product_name UNIQUE (fetch_date, institute_code, product_name)
    );
    CREATE INDEX IF NOT EXISTS ix_fd_rates_fetch_date
        ON "fd_rates" (fetch_date);
    CREATE INDEX IF NOT EXISTS ix_fd_rates_tenure_category
        ON "fd_rates" (tenure_category);
    CREATE INDEX IF NOT EXISTS ix_fd_rates_interest_pct
        ON "fd_rates" (interest_pct);
    """,

    "fd_rate_summary": """
    CREATE TABLE IF NOT EXISTS "fd_rate_summary" (
        id SERIAL PRIMARY KEY,
        fetch_date TEXT NOT NULL,
        avg_rate_pct TEXT,
        max_rate_pct TEXT,
        min_rate_pct TEXT,
        best_bank_name TEXT,
        best_bank_rate TEXT,
        best_tenure TEXT,
        rate_vs_prev_pct TEXT,
        rate_direction TEXT,
        fd_score_signal TEXT,
        total_products TEXT,
        inserted_at TIMESTAMPTZ DEFAULT NOW(),
        CONSTRAINT ux_fd_rate_summary_fetch_date UNIQUE (fetch_date)
    );
    CREATE INDEX IF NOT EXISTS ix_fd_rate_summary_fetch_date
        ON "fd_rate_summary" (fetch_date);
    """,
}

TABLE_COLUMNS: dict[str, list[str]] = {
    "price_history": ["date", "symbol", "open", "high", "low", "close", "ltp", "volume", "turnover", "vwap", "prev_close", "transactions", "conf_score", "avg_120d", "avg_180d", "week52_high", "week52_low", "source"],
    "market_breadth": ["date", "advancing", "declining", "unchanged", "new_52w_high", "new_52w_low", "total_turnover_npr", "total_volume", "breadth_score", "market_signal", "nepse_index", "nepse_change_pct", "timestamp"],
    "watchlist": ["symbol", "company", "sector", "added_date", "fundamental_score", "technical_score", "combined_score", "last_updated", "sector_momentum", "dividend_yield_pct", "pe_ratio", "eps", "npl_pct", "car_pct", "week52_high", "week52_low", "pct_from_52w_high", "notes"],
    "portfolio": ["symbol", "entry_date", "entry_price", "shares", "total_cost", "current_price", "current_value", "pnl_npr", "pnl_pct", "peak_price", "stop_type", "stop_level", "trail_active", "trail_stop", "status", "exit_date", "exit_price", "exit_reason"],
    "market_log": ["date", "time", "symbol", "sector", "action", "confidence", "entry_price", "stop_loss", "target", "allocation_npr", "shares", "breakeven", "risk_reward", "rsi_14", "ema_20", "ema_50", "ema_200", "macd_line", "macd_signal", "volume", "volume_ratio", "obv_trend", "vwap", "atr_14", "bollinger_upper", "bollinger_lower", "support_level", "resistance_level", "candle_pattern", "conf_score", "pe_ratio", "eps", "roe", "npl_pct", "fundamental_score", "geo_score", "macro_score", "reasoning", "outcome", "actual_pnl", "exit_price", "exit_date", "exit_reason", "dual_audit", "gpt_verdict", "timestamp"],
    "indicators": ["symbol", "date", "ltp", "prev_close", "volume", "history_days", "rsi_14", "rsi_signal", "ema_20", "ema_50", "ema_200", "ema_trend", "ema_20_50_cross", "ema_50_200_cross", "macd_line", "macd_signal", "macd_histogram", "macd_cross", "bb_upper", "bb_middle", "bb_lower", "bb_width", "bb_pct_b", "bb_signal", "atr_14", "atr_pct", "obv", "obv_trend", "tech_score", "tech_signal", "timestamp"],
    "candle_patterns": ["pattern_name", "type", "tier", "nepal_win_rate_pct", "sample_size", "avg_gain_pct", "best_sector", "best_rsi_range", "volume_condition", "reliability", "notes"],
    "candle_signals": ["symbol", "date", "pattern_name", "signal", "tier", "confidence", "volume_confirmed", "candles_used", "description", "timestamp"],
    "geopolitical_data": ["date", "time", "crude_price", "crude_change_pct", "vix", "vix_level", "nifty", "nifty_change_pct", "dxy", "gold_price", "geo_score", "status", "key_event", "timestamp"],
    "nepal_pulse": ["date", "time", "policy_rate", "policy_rate_change", "ccd_ratio", "crr", "slr", "nrb_event", "sebon_event", "circuit_breaker", "ipo_fpo_active", "ipo_fpo_detail", "govt_stability", "political_event", "budget_season", "budget_event", "remittance_yoy_pct", "inflation_pct", "forex_reserve_months", "trade_deficit_npr", "bandh_today", "bandh_detail", "load_shedding_hrs", "nepal_score", "nepal_status", "key_event", "source", "timestamp"],
    "macro_data": ["indicator", "value", "unit", "direction", "impact", "last_updated", "source"],
    "nrb_monthly": ["period", "fiscal_year", "month_number", "is_annual", "nepse_index", "policy_rate", "bank_rate", "crr_percentage", "slr_percentage", "cpi_inflation", "credit_growth_rate", "liquidity_injected_billion", "remittance_yoy_change_pct", "fx_reserve_months", "bop_overall_balance_usd_m", "bop_current_account_usd_m", "bop_status", "bop_trend", "overall_sentiment", "forward_guidance", "key_risks"],
    "fundamentals": ["symbol", "company", "sector", "quarter", "fiscal_year", "eps", "pe_ratio", "bvps", "pbv_ratio", "roe", "roa", "dps", "dividend_yield", "net_profit_npr", "revenue_npr", "net_profit_growth_pct", "revenue_growth_pct", "debt_to_equity", "market_cap_npr", "car_pct", "npl_pct", "nim_pct", "cd_ratio", "report_date", "data_source"],
    "sector_momentum": ["date", "sector", "weekly_return_pct", "monthly_return_pct", "avg_volume_change_pct", "momentum_score", "status", "top_stock_1", "top_stock_2", "catalyst", "last_updated"],
    "corporate_events": ["symbol", "company", "event_type", "announcement_date", "event_date", "book_close_date", "details", "expected_impact_pct", "days_until_event", "status", "source"],
    "dividend_announcements": ["symbol", "company", "sector", "announcement_date", "fiscal_year", "dividend_type", "cash_dividend_pct", "bonus_share_pct", "total_dividend_pct", "book_close_date", "direction", "prev_dividend_pct", "source", "scraped_at"],
    "dividend_pattern_study": ["symbol", "announcement_date", "sector", "direction", "price_drift_d10", "price_drift_d6", "price_drift_d4", "price_drift_d2", "vol_ratio_d6", "vol_ratio_d4", "vol_ratio_d2", "vol_ratio_d1", "rsi_d6", "rsi_d4", "obv_trend_d6_to_d1", "atr_ratio_d6", "macd_state_d4", "return_d0", "return_d1", "return_d2_d9", "vs_nepse_d1", "pattern_detected", "pattern_type", "pattern_strength", "entry_feasible", "optimal_entry_day", "run_date"],
    "trade_journal": ["created_at", "symbol", "sector", "paper_mode", "entry_date", "entry_price", "shares", "allocation_npr", "primary_signal", "secondary_signal", "candle_pattern", "confidence_at_entry", "rsi_entry", "macd_hist_entry", "bb_signal_entry", "ema_trend_entry", "obv_trend_entry", "conf_score_entry", "volume_ratio_entry", "atr_pct_entry", "market_state_entry", "geo_score_entry", "nepal_score_entry", "combined_geo_entry", "nepse_index_entry", "stop_loss_planned", "target_planned", "hold_days_planned", "exit_date", "exit_price", "exit_reason", "market_state_exit", "geo_score_exit", "nepal_score_exit", "combined_geo_exit", "nepse_index_exit", "hold_days_actual", "return_pct", "pnl_npr", "result", "geo_delta", "nepal_delta", "combined_geo_delta", "nepse_return_pct", "alpha_vs_nepse", "loss_cause", "lesson_ids"],
    "learning_hub": ["created_at", "lesson_type", "source", "symbol", "sector", "applies_to", "condition", "finding", "action", "trade_count", "win_count", "loss_count", "win_rate", "avg_return_pct", "avg_pnl_npr", "confidence_level", "loss_cause_primary", "geo_delta_avg", "nepal_delta_avg", "alpha_vs_nepse_avg", "active", "superseded_by", "last_validated", "validation_count", "trade_journal_ids"],
    "news_sentiment": ["date", "overall_score", "banking_score", "hydro_score", "insurance_score", "microfinance_score", "top_positive_news", "top_negative_news", "key_stock_mentions", "source_count", "timestamp"],
    "backtest_results": ["test_name", "parameter_tested", "optimal_value", "win_rate_at_optimal", "sample_size", "confidence", "date_run", "notes"],
    "capital_allocation": ["date", "market_state", "nepse_vs_200dma", "stocks_pct", "fd_pct", "savings_pct", "od_pct", "fd_rate_used", "expected_return", "reasoning", "review_date", "status"],
    "financial_advisor": ["date", "recommendation_type", "market_phase", "confidence_pct", "capital_in_stocks_pct", "capital_in_fd_pct", "capital_in_savings_pct", "capital_in_od_pct", "three_month_outlook", "expected_return_pct", "fd_rate_used", "trigger_to_change", "review_date", "actual_outcome", "was_forecast_correct"],
    "financials": ["kpi_name", "current_value", "target_value", "alert_level", "status", "last_updated", "notes"],
    "settings": ["key", "value", "description", "last_updated", "set_by"],
    "db_schema": ["migration_id", "name", "applied_at", "rolled_back_at", "status", "notes"],
    "nepse_indices": ["date", "index_id", "index_name", "current_value", "high", "low", "change_abs", "change_pct", "week52_high", "week52_low", "turnover", "volume", "transactions", "source"],
    "macro_stat_results": ["variable", "variable_label", "lag_months", "spearman_rho", "p_value", "p_corrected", "significant", "effect_size", "n_pairs", "rho_3m_forward", "p_3m_forward", "n_pairs_3m", "n_total_tests", "alpha_corrected", "run_date", "notes"],
    "fd_rates": ["fetch_date", "institute_code", "institute_name", "product_name", "interest_rate", "interest_pct", "tenure_label", "tenure_months", "tenure_category", "minimum_balance", "institute_type", "source"],
    "fd_rate_summary": ["fetch_date", "avg_rate_pct", "max_rate_pct", "min_rate_pct", "best_bank_name", "best_bank_rate", "best_tenure", "rate_vs_prev_pct", "rate_direction", "fd_score_signal", "total_products"],
}
